#!/bin/sh
# HyperChat one-command server setup - the cherry-picked alpha path.
#
# Run this ON THE HOST that should become the server, from inside the repo:
#
#     ./deploy/quickstart.sh                     # plain http://<host-ip>/
#     ./deploy/quickstart.sh alpha.example.com   # automatic https + voice
#     ./deploy/quickstart.sh --dry-run           # print the plan, change nothing
#
# What it does: installs Docker if missing (get.docker.com), generates
# .env.production with fresh secrets (SEED_DEMO on: tester1..tester3 /
# hyperion-alpha), builds the image, starts the stack, waits for health and
# prints the URL. Re-running it is safe: existing .env.production and
# volumes are never touched.
set -eu

DOMAIN=""
DRY_RUN=0
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1 ;;
    -h|--help)
      echo "usage: $0 [domain] [--dry-run]"
      echo "  no domain : plain HTTP on host port \${PUBLIC_PORT:-80} (quick test mode)"
      echo "  domain    : automatic HTTPS on 80/443 - also enables voice calls"
      echo "  --dry-run : print the plan without changing anything"
      exit 0 ;;
    *) DOMAIN="$arg" ;;
  esac
done

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"
if [ ! -f docker-compose.yml ] || [ ! -f Dockerfile ]; then
  echo "error: run this from inside the hyperchat repo (docker-compose.yml not found next to it)" >&2
  exit 1
fi

say() { printf '\n==> %s\n' "$*"; }

SUDO=""
[ "$(id -u)" = 0 ] || SUDO="sudo"

rand_hex() {
  n="$1"
  out=""
  if command -v openssl >/dev/null 2>&1; then
    out="$(openssl rand -hex "$n" 2>/dev/null || true)"
  fi
  if [ -z "$out" ]; then
    out="$(head -c "$n" /dev/urandom | od -An -tx1 | tr -d ' \n')"
  fi
  printf '%s' "$out"
}

if [ "$DRY_RUN" = 1 ]; then
  say "dry run: printing the plan, changing nothing"
fi

# ---- 1. docker --------------------------------------------------------------
COMPOSE=""
if command -v docker >/dev/null 2>&1; then
  if docker compose version >/dev/null 2>&1; then
    COMPOSE="docker compose"
  elif command -v docker-compose >/dev/null 2>&1; then
    COMPOSE="docker-compose"
  fi
fi

if [ -z "$COMPOSE" ]; then
  case "$(uname -s)" in
    Darwin)
      echo "error: macOS - install Docker Desktop from docker.com, then re-run" >&2
      exit 1 ;;
  esac
  if ! command -v curl >/dev/null 2>&1; then
    echo "error: curl is required to install docker" >&2
    exit 1
  fi
  if [ -n "$SUDO" ] && ! command -v sudo >/dev/null 2>&1; then
    echo "error: docker is missing and there is no sudo - become root and re-run" >&2
    exit 1
  fi
  say "docker not found - installing it via get.docker.com (one-time, about a minute)"
  [ "$DRY_RUN" = 1 ] || curl -fsSL https://get.docker.com | $SUDO sh
  COMPOSE="docker compose"
fi

# non-root users need the docker group; fail with the fix instead of a wall of permission errors
if [ "$DRY_RUN" = 0 ]; then
  docker info >/dev/null 2>&1 || {
    echo "error: docker is installed but not usable by this user." >&2
    echo "  fix: sudo usermod -aG docker \$USER  then log out and back in" >&2
    exit 1
  }
fi

# ---- 2. secrets -------------------------------------------------------------
if [ ! -f .env.production ]; then
  say "generating .env.production (fresh secrets, SEED_DEMO on)"
  if [ "$DRY_RUN" = 1 ]; then
    echo "  would write: JWT_SECRET, INTERNAL_TOKEN (random), SEED_DEMO=true${DOMAIN:+, SITE_ADDRESS=$DOMAIN}"
  else
    {
      echo "# generated by deploy/quickstart.sh on $(date)"
      echo "# cherry-picked alpha mode: remove SEED_DEMO for a clean slate"
      echo "JWT_SECRET=$(rand_hex 32)"
      echo "INTERNAL_TOKEN=$(rand_hex 24)"
      echo "SEED_DEMO=true"
      echo "SITE_ADDRESS=${DOMAIN}"
    } > .env.production
    chmod 600 .env.production
  fi
else
  say ".env.production exists - keeping its secrets"
  if [ -n "$DOMAIN" ]; then
    # https mode is selected by the domain argument; the runtime needs to
    # agree, so make sure SITE_ADDRESS is set to it
    if ! grep -q "^SITE_ADDRESS=$DOMAIN" .env.production 2>/dev/null; then
      say "setting SITE_ADDRESS=$DOMAIN in .env.production"
      if [ "$DRY_RUN" = 0 ]; then
        if grep -q '^SITE_ADDRESS=' .env.production 2>/dev/null; then
          sed -i.bak "s|^SITE_ADDRESS=.*|SITE_ADDRESS=$DOMAIN|" .env.production && rm -f .env.production.bak
        else
          echo "SITE_ADDRESS=$DOMAIN" >> .env.production
        fi
      fi
    fi
  fi
fi

# ---- 3. build + start -------------------------------------------------------
PUBLIC_PORT="${PUBLIC_PORT:-80}"
export PUBLIC_PORT

if [ -n "$DOMAIN" ]; then
  RUN="$COMPOSE -f docker-compose.yml -f deploy/compose.domain.yml up -d --build"
  say "https mode for $DOMAIN (the DNS A-record must already point at this machine)"
else
  RUN="$COMPOSE up -d --build"
  say "quick http mode on host port $PUBLIC_PORT"
fi

if [ "$DRY_RUN" = 1 ]; then
  echo "  would run: $RUN"
else
  $RUN
fi

# ---- 4. health + summary ----------------------------------------------------
IP="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
[ -n "$IP" ] || IP="<this machine's ip>"

if [ -n "$DOMAIN" ]; then
  URL="https://$DOMAIN"
  PROBE_PORT=80
else
  SUFFIX=""
  [ "$PUBLIC_PORT" != "80" ] && SUFFIX=":$PUBLIC_PORT" || true
  URL="http://$IP$SUFFIX"
  PROBE_PORT="$PUBLIC_PORT"
fi

if [ "$DRY_RUN" = 0 ] && command -v curl >/dev/null 2>&1; then
  say "waiting for the app to answer (first build takes a few minutes)"
  i=0
  while [ "$i" -lt 40 ]; do
    if curl -fsS -o /dev/null --max-time 3 "http://127.0.0.1:${PROBE_PORT}/" 2>/dev/null; then
      break
    fi
    i=$((i + 1))
    sleep 3
  done
  if [ "$i" -ge 40 ]; then
    echo "the app did not answer in time - inspect with: $COMPOSE logs app | tail -50" >&2
    exit 1
  fi
  say "healthy"
fi

say "done. the alpha is live at $URL"
echo "  tester accounts (SEED_DEMO): tester1 / tester2 / tester3, password: hyperion-alpha"
echo "  first real account you register becomes ADMIN; data lives in the 'hyperchat-data' volume"
if [ -z "$DOMAIN" ]; then
  echo "  voice calls need https: re-run later with a domain - $0 alpha.example.com"
fi
echo "  logs: $COMPOSE logs -f app"
