import { flagSrc } from './flags'

/** Every bundled flag glyph (public/flags) as a picker-ready emoji def.
 *  Windows renders regional-indicator pairs as letters ("US"), so the
 *  picker draws these from the twemoji set via EmojiText -> FlagText,
 *  and search works by country name, code and common aliases. */

/** ISO pair -> searchable names. Order matches the emoji category list. */
export const FLAG_CATALOG: [code: string, names: string][] = [
  ['ac', 'ascension island'],
  ['ad', 'andorra'],
  ['ae', 'united arab emirates uae'],
  ['af', 'afghanistan'],
  ['ag', 'antigua barbuda'],
  ['ai', 'anguilla'],
  ['al', 'albania'],
  ['am', 'armenia'],
  ['ao', 'angola'],
  ['aq', 'antarctica'],
  ['ar', 'argentina'],
  ['as', 'american samoa'],
  ['at', 'austria'],
  ['au', 'australia aussie'],
  ['aw', 'aruba'],
  ['ax', 'aland islands'],
  ['az', 'azerbaijan'],
  ['ba', 'bosnia herzegovina'],
  ['bb', 'barbados'],
  ['bd', 'bangladesh'],
  ['be', 'belgium'],
  ['bf', 'burkina faso'],
  ['bg', 'bulgaria'],
  ['bh', 'bahrain'],
  ['bi', 'burundi'],
  ['bj', 'benin'],
  ['bl', 'saint barthelemy st barts'],
  ['bm', 'bermuda'],
  ['bn', 'brunei'],
  ['bo', 'bolivia'],
  ['bq', 'caribbean netherlands'],
  ['br', 'brazil brasil'],
  ['bs', 'bahamas'],
  ['bt', 'bhutan'],
  ['bv', 'bouvet island'],
  ['bw', 'botswana'],
  ['by', 'belarus'],
  ['bz', 'belize'],
  ['ca', 'canada'],
  ['cc', 'cocos islands'],
  ['cd', 'dr congo drc'],
  ['cf', 'central african republic'],
  ['cg', 'congo brazzaville'],
  ['ch', 'switzerland swiss'],
  ['ci', 'cote divoire ivory coast'],
  ['ck', 'cook islands'],
  ['cl', 'chile'],
  ['cm', 'cameroon'],
  ['cn', 'china prc'],
  ['co', 'colombia'],
  ['cp', 'clipperton island'],
  ['cr', 'costa rica'],
  ['cu', 'cuba'],
  ['cv', 'cabo verde cape verde'],
  ['cw', 'curacao'],
  ['cx', 'christmas island'],
  ['cy', 'cyprus'],
  ['cz', 'czechia czech republic'],
  ['de', 'germany deutschland'],
  ['dg', 'diego garcia'],
  ['dj', 'djibouti'],
  ['dk', 'denmark danish'],
  ['dm', 'dominica'],
  ['do', 'dominican republic'],
  ['dz', 'algeria'],
  ['ea', 'ceuta melilla'],
  ['ec', 'ecuador'],
  ['ee', 'estonia'],
  ['eg', 'egypt'],
  ['eh', 'western sahara'],
  ['er', 'eritrea'],
  ['es', 'spain espana'],
  ['et', 'ethiopia'],
  ['eu', 'european union eu'],
  ['fi', 'finland finnish'],
  ['fj', 'fiji'],
  ['fk', 'falkland islands'],
  ['fm', 'micronesia'],
  ['fo', 'faroe islands'],
  ['fr', 'france french'],
  ['ga', 'gabon'],
  ['gb', 'united kingdom uk great britain britain england'],
  ['gd', 'grenada'],
  ['ge', 'georgia'],
  ['gf', 'french guiana'],
  ['gg', 'guernsey'],
  ['gh', 'ghana'],
  ['gi', 'gibraltar'],
  ['gl', 'greenland'],
  ['gm', 'gambia'],
  ['gn', 'guinea'],
  ['gp', 'guadeloupe'],
  ['gq', 'equatorial guinea'],
  ['gr', 'greece hellenic'],
  ['gs', 'south georgia sandwich'],
  ['gt', 'guatemala'],
  ['gu', 'guam'],
  ['gw', 'guinea-bissau'],
  ['gy', 'guyana'],
  ['hk', 'hong kong'],
  ['hm', 'heard mcdonald islands'],
  ['hn', 'honduras'],
  ['hr', 'croatia'],
  ['ht', 'haiti'],
  ['hu', 'hungary'],
  ['ic', 'canary islands'],
  ['id', 'indonesia'],
  ['ie', 'ireland irish'],
  ['il', 'israel'],
  ['im', 'isle of man'],
  ['in', 'india'],
  ['io', 'british indian ocean territory'],
  ['iq', 'iraq'],
  ['ir', 'iran persia'],
  ['is', 'iceland'],
  ['it', 'italy italiano'],
  ['je', 'jersey'],
  ['jm', 'jamaica'],
  ['jo', 'jordan'],
  ['jp', 'japan nihon'],
  ['ke', 'kenya'],
  ['kg', 'kyrgyzstan'],
  ['kh', 'cambodia'],
  ['ki', 'kiribati'],
  ['km', 'comoros'],
  ['kn', 'saint kitts nevis'],
  ['kp', 'north korea dprk'],
  ['kr', 'south korea korea'],
  ['kw', 'kuwait'],
  ['ky', 'cayman islands'],
  ['kz', 'kazakhstan'],
  ['la', 'laos'],
  ['lb', 'lebanon'],
  ['lc', 'saint lucia'],
  ['li', 'liechtenstein'],
  ['lk', 'sri lanka ceylon'],
  ['lr', 'liberia'],
  ['ls', 'lesotho'],
  ['lt', 'lithuania'],
  ['lu', 'luxembourg'],
  ['lv', 'latvia'],
  ['ly', 'libya'],
  ['ma', 'morocco'],
  ['mc', 'monaco'],
  ['md', 'moldova'],
  ['me', 'montenegro'],
  ['mf', 'saint martin'],
  ['mg', 'madagascar'],
  ['mh', 'marshall islands'],
  ['mk', 'north macedonia macedonia'],
  ['ml', 'mali'],
  ['mm', 'myanmar burma'],
  ['mn', 'mongolia'],
  ['mo', 'macau macao'],
  ['mp', 'northern mariana islands'],
  ['mq', 'martinique'],
  ['mr', 'mauritania'],
  ['ms', 'montserrat'],
  ['mt', 'malta'],
  ['mu', 'mauritius'],
  ['mv', 'maldives'],
  ['mw', 'malawi'],
  ['mx', 'mexico'],
  ['my', 'malaysia'],
  ['mz', 'mozambique'],
  ['na', 'namibia'],
  ['nc', 'new caledonia'],
  ['ne', 'niger'],
  ['nf', 'norfolk island'],
  ['ng', 'nigeria'],
  ['ni', 'nicaragua'],
  ['nl', 'netherlands holland dutch'],
  ['no', 'norway norwegian'],
  ['np', 'nepal'],
  ['nr', 'nauru'],
  ['nu', 'niue'],
  ['nz', 'new zealand kiwi'],
  ['om', 'oman'],
  ['pa', 'panama'],
  ['pe', 'peru'],
  ['pf', 'french polynesia tahiti'],
  ['pg', 'papua new guinea'],
  ['ph', 'philippines pinas'],
  ['pk', 'pakistan'],
  ['pl', 'poland polish'],
  ['pm', 'saint pierre miquelon'],
  ['pr', 'puerto rico'],
  ['ps', 'palestine'],
  ['pt', 'portugal portuguese'],
  ['pn', 'pitcairn islands'],
  ['pw', 'palau'],
  ['py', 'paraguay'],
  ['qa', 'qatar'],
  ['re', 'reunion'],
  ['ro', 'romania'],
  ['rs', 'serbia'],
  ['ru', 'russia'],
  ['rw', 'rwanda'],
  ['sa', 'saudi arabia'],
  ['sb', 'solomon islands'],
  ['sc', 'seychelles'],
  ['sd', 'sudan'],
  ['se', 'sweden swedish'],
  ['sg', 'singapore'],
  ['sh', 'saint helena'],
  ['si', 'slovenia'],
  ['sj', 'svalbard jan mayen'],
  ['sk', 'slovakia'],
  ['sl', 'sierra leone'],
  ['sm', 'san marino'],
  ['sn', 'senegal'],
  ['so', 'somalia'],
  ['sr', 'suriname'],
  ['ss', 'south sudan'],
  ['st', 'sao tome principe'],
  ['sv', 'el salvador'],
  ['sx', 'sint maarten'],
  ['sy', 'syria'],
  ['sz', 'eswatini swaziland'],
  ['ta', 'tristan da cunha'],
  ['tc', 'turks caicos'],
  ['td', 'chad'],
  ['tf', 'french southern territories'],
  ['tg', 'togo'],
  ['th', 'thailand'],
  ['tj', 'tajikistan'],
  ['tk', 'tokelau'],
  ['tl', 'timor-leste east timor'],
  ['tm', 'turkmenistan'],
  ['tn', 'tunisia'],
  ['to', 'tonga'],
  ['tr', 'turkiye turkey'],
  ['tt', 'trinidad tobago'],
  ['tv', 'tuvalu'],
  ['tw', 'taiwan'],
  ['tz', 'tanzania'],
  ['ua', 'ukraine'],
  ['ug', 'uganda'],
  ['um', 'us minor outlying islands'],
  ['un', 'united nations un'],
  ['us', 'united states usa america'],
  ['uy', 'uruguay'],
  ['uz', 'uzbekistan'],
  ['va', 'vatican city holy see'],
  ['vc', 'saint vincent grenadines'],
  ['ve', 'venezuela'],
  ['vg', 'british virgin islands'],
  ['vi', 'us virgin islands'],
  ['vn', 'vietnam'],
  ['vu', 'vanuatu'],
  ['wf', 'wallis futuna'],
  ['ws', 'samoa'],
  ['xk', 'kosovo'],
  ['ye', 'yemen'],
  ['yt', 'mayotte'],
  ['za', 'south africa rsa'],
  ['zm', 'zambia'],
  ['zw', 'zimbabwe'],
]

const REGIONAL_A = 0x1f1e6

/** 'us' -> '🇺🇸' */
export function codeToFlagEmoji(code: string): string {
  return String.fromCodePoint(
    REGIONAL_A + (code.charCodeAt(0) - 97),
    REGIONAL_A + (code.charCodeAt(1) - 97)
  )
}

/** Picker-ready defs: the emoji char plus searchable names. The ISO code
 *  rides FIRST so it becomes the :us: / :il: / :de: shortcode (the emoji
 *  kit derives shortcodes from the first name word) and ranks first in
 *  search. */
export const FLAG_EMOJIS: { char: string; names: string }[] = FLAG_CATALOG.map(([code, names]) => ({
  char: codeToFlagEmoji(code),
  names: `${code} ${names}`,
}))

/** ':us:' style shortcode -> bundled glyph path (null when the two-letter
 *  code has no shipped flag). Lets old messages (and other clients) show
 *  real flags instead of literal :il: tokens. */
export function flagShortcodeSrc(code: string): string | null {
  if (!/^[a-z]{2}$/.test(code)) return null
  try {
    return flagSrc(codeToFlagEmoji(code))
  } catch {
    return null
  }
}
